config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about' => 'home#about', as: 'about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  get 'users/:user_id/follows' => 'relationships#following', as: 'followings'
  get 'users/:user_id/followers' => 'relationships#follower', as: 'followers'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'search' => 'searches#search'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, destroy: false

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :follower, source: :followed
  has_many :follower_users, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_users.include?(user)
  end

  def self.search(search, word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backword_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  # prefecture_codeからprefecture_nameに変換するメソッド(カラム設定後に記述)
  # prefecture_codeはuserが持っているカラム
 include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # バリデーションの前に送信されたaddressの値によってジオコーディング(緯度経度の算出)を行う
  geocoded_by :address
  after_validation :geocode
  # geocoderで使用するaddressを定義
  def address
    self.prefecture_code + self.address_city + self.address_street
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name%></td>
				<td>
					<p>
						<%= "フォロー数: #{user.follower.count}" %>
					</p>
				</td>
				<td>
					<p>
						<%= "フォワー数: #{user.followed.count}" %>
					</p>
				</td>
				<td>
					<p>
						<% if current_user.following?(user) %>
				     		<%= link_to "フォローを外す", unfollow_path(user.id), method: :post %>
					 	<% else %>
					   		<%= link_to "フォローする", follow_path(user.id), method: :post %>
					  	<% end %>
					 </p>
				</td>
				<td>
					<%= link_to "Show", user, class: "user_#{user.id}" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
		<tr>
			<%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %>
		</tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th><%= link_to user.follower.count, followings_path(user_id: user.id) %></th>
		</tr>

		<tr>
			<th>followers</th>
			<th><%=link_to user.followed.count, followers_path(user_id: user.id) %></th>
		</tr>
</table>

<% if user == current_user %>
	<div class="row">
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% else %>
	<div class="row">
		<% if current_user.following?(user) %>
			<%= link_to "フォローを外す", unfollow_path(user.id), method: :post, class: "col-xs-6 col-xs-offset-3 btn btn-primary" %>
		<% else %>
    		<%= link_to "フォローする", follow_path(user.id), method: :post, class: "col-xs-6 col-xs-offset-3 btn btn-success" %>
  		<% end %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<%= render 'layouts/errors', obj: @user %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">

		<h2>Users</h2>
		<!--users一覧 -->
		<%= render 'users/index', users: @users %>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">

		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'books/index', books: @books %>
		<!--books一覧 -->
	</div>
	<%# マイページの場合、ここに住所情報 %>
    <% if @user.id == current_user.id %>
        <div class="your_map">
        	<h2>Your MAP</h2>
          <div id="map" data-address="<%= @user.address %>" data-prefecture="<%= @user.prefecture_code %>" ></div>
        </div>
    <% end %>
    <style>
	#map{
  		height: 400px;
	}
	</style>
</div>

<script>
  let geocoder
  function initMap() {
    geocoder = new google.maps.Geocoder()
    var initMap = document.getElementById('map')
    console.log(initMap)
    // latitude,longitudeから位置を特定
    var map = new google.maps.Map(initMap, {
              zoom: 15,
              });

  var inputAddress = initMap.getAttribute('data-address')
  console.log(inputAddress)
  // geocodingしたあとmapを移動
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      // map.setCenterで地図が移動
      map.setCenter(results[0].geometry.location);

      // google.maps.MarkerでGoogleMap上の指定位置にマーカが立つ
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
  }
</script>

<%# アドレス内 key= APIキーを記述 %>
<%# Githubなどにアップロードすべきでない第三者に漏洩すると危険な外部のAPIキーの情報を環境変数として管理 →.env %>
<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>