config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about' => 'home#about', as: 'about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end

  get 'users/:user_id/follows' => 'relationships#following', as: 'followings'
  get 'users/:user_id/followers' => 'relationships#follower', as: 'followers'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'search' => 'searches#search'

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search, word)
		if search == "forward_match"
			@book = Book.where("title LIKE?","#{word}%")
		elsif search == "backword_match"
			@book = Book.where("title LIKE?","%#{word}")
		elsif search == "perfect_match"
			@book = Book.where("title LIKE?","#{word}")
		elsif search == "partial_match"
			@book = Book.where("title LIKE?","%#{word}%")
		else
			@book = Book.all
		end
	end

	#presence trueは空欄の場合を意味する。
	validates :title, presence: true, length: {maximum: 200}
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book_new = Book.new
  	@book = Book.find(params[:id])
    @book_comment =BookComment.new
    @user = @book.user
  end

  def index
  	@books = Book.all
    @book =  Book.new
     #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
  	@book.user_id = current_user.id

    if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
      @user = current_user
  		@books = Book.all
  		render ("books/index")
  	end
  end

  def edit
  end



  def update
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<td>
	<%= link_to user_path(book.user) do %>
		<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
	<% end %>
</td>
<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
<td><%= book.body %></td>
<td>
	<% if book.favorited_by?(current_user) %>
		<%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
        	<span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
    	<% end %>
    <% else %>
        <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
            <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
     	<% end %>
    <% end %>
</td>
<td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_comment.html.erb
<% book_comments.each do |book_comment| %>
	<tr>
		<td>
			<%= link_to user_path(book_comment.user) do %>
				<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
				<%= book_comment.user.name %>
			<% end %>
		</td>
		<td>
			<%= book_comment.comment %>
		</td>

		<% if book_comment.user == current_user %>
			<td><%= link_to "Destroy",book_book_comment_path(book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, remote: true, class: "btn-sm btn-danger" %>
			</td>
		<% end %>
	</tr>
<% end %>

app/views/books/_detail.html.erb
<td>
	<%= link_to user_path(book.user) do %>
		<%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
		<%= book.user.name %>
	<% end %>
</td>
<td>
	<%= link_to book.title, book %>
</td>
<td>
	<%= book.body %>
</td>

<td>
    <% if book.favorited_by?(current_user) %>
        <%= link_to book_favorites_path(book, redirect_id: 0), method: :delete, remote: true do %>
            <span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>
        <% end %>
    <% else %>
        <%= link_to book_favorites_path(book, redirect_id: 0), method: :post, remote: true do %>
            <span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %></span>
    	<% end %>
    <% end %>
</td>

<td>
    コメント数：<%= book.book_comments.count %>
</td>

<% if book.user == current_user %>
	<td><%= link_to "Edit",edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
	<td><%= link_to "Destroy",book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{book.id}" %></td>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% books.each do |book| %>
			<tr class="book_<%= book.id %>">
				<%= render '/books/book', book: book %>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title, "Title" %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body, "Opinion" %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render 'layouts/errors', obj: @book %>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
|
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'books/index', books:@books %>
		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<%= render 'layouts/errors', obj: @book %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<tr class="book_<%= @book.id %>">
				<%= render 'books/detail', book: @book %>
			</tr>
		</table>

		<table class="show-tb comment_<%= @book.id %>">
			<%= render 'books/comment', book_comments: @book.book_comments %>
		</table>

		<div class="comment-form">
			<%= form_with model:[@book, @book_comment], date: {remote: true} do |f| %>
				<%= f.text_area :comment, rows:'5', class: "form-control" %>
				<%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
		</div>
	</div>
</div>